# platform :ios, '9.0'
use_frameworks!
target 'SecondHand2iOS' do
  pod 'IQKeyboardManagerSwift'
  pod 'DropDown'
  pod 'Firebase/RemoteConfig'

  target 'SecondHand2iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SecondHand2iOSUITests' do
    # Pods for testing
  end

end
