# platform :ios, '9.0'

target 'SecondHand2iOS' do
  pod 'IQKeyboardManagerSwift'
  pod 'DropDown'

  target 'SecondHand2iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SecondHand2iOSUITests' do
    # Pods for testing
  end

end
